language: node_js
node_js:
  - stable
cache:
  yarn: true

script: npm test
after_success:
  - yarn deploy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    tags: true
  